name: Run Unit Tests
run-name: ${{ github.actor }} is running unit tests 🚀
on:
  push:
    branches:
      - master
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        uses: robherley/go-test-action@v0
